headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "/home/zazool/rebootitsolutions"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/css/*"

[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/js/*"

[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/images/*"

[headers.values]
Cache-Control = "public, max-age=31536000"

[[redirects]]
from = "/home"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/what-i-do"
to = "/services.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 404.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]